/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Frames;

import modelUi.studyante;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author Asus
 */
public class DashboardSidButtons extends javax.swing.JFrame {

     private ArrayList<studyante> stu; // Store student list
    private statistics statsPanel; // Store statistics panel

    public DashboardSidButtons(ArrayList<studyante> students) {
        this.stu = students;
        this.statsPanel = new statistics(stu); // Create statistics panel once
        initComponents();
        this.setLocationRelativeTo(null);
    }

    // ✅ Method to switch to Statistics Panel
    private void switchToStatistics() {
        statsPanel.refreshData(stu); // Update data before showing
        ViewPanel.setViewportView(statsPanel); // Show existing panel
        ViewPanel.revalidate(); // Refresh UI
        ViewPanel.repaint();
    }

    // ✅ Label Hover Effects
    public void LblHover(JLabel lbl) {
        lbl.setForeground(Color.BLACK);
        lbl.setFont(new java.awt.Font("Segoe Print", 1, 26));
    }

    public void LblHoverOut(JLabel lbl) {
        lbl.setForeground(Color.BLACK);
        lbl.setFont(new java.awt.Font("Segoe Print", 0, 24));
    }

    public void LblHoverOutwo(JLabel lbl) {
        lbl.setForeground(Color.BLACK);
        lbl.setFont(new java.awt.Font("Segoe Print", 0, 23));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblStatistics = new javax.swing.JLabel();
        lblStuData = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        myPanel1 = new GUI.CustomComponents.MyPanel("picture.jpg");
        ViewPanel = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        lblStatistics.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        lblStatistics.setForeground(new java.awt.Color(0, 0, 0));
        lblStatistics.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatistics.setText("STATISTICS");
        lblStatistics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStatisticsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblStatisticsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblStatisticsMouseExited(evt);
            }
        });

        lblStuData.setFont(new java.awt.Font("Segoe Print", 1, 23)); // NOI18N
        lblStuData.setForeground(new java.awt.Color(0, 0, 0));
        lblStuData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStuData.setText("STUDENTS DATA");
        lblStuData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStuDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblStuDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblStuDataMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LOG OUT");

        myPanel1.setBackground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout myPanel1Layout = new javax.swing.GroupLayout(myPanel1);
        myPanel1.setLayout(myPanel1Layout);
        myPanel1Layout.setHorizontalGroup(
            myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        myPanel1Layout.setVerticalGroup(
            myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStuData, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(lblStatistics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146)
                .addComponent(lblStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStuData, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ViewPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblStatisticsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStatisticsMouseClicked
       switchToStatistics();
    }//GEN-LAST:event_lblStatisticsMouseClicked

    private void lblStatisticsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStatisticsMouseEntered
        LblHover(lblStatistics);
    }//GEN-LAST:event_lblStatisticsMouseEntered

    private void lblStatisticsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStatisticsMouseExited
        LblHoverOut(lblStatistics);
    }//GEN-LAST:event_lblStatisticsMouseExited

    private void lblStuDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStuDataMouseClicked
        ViewPanel.setViewportView(new studentData(stu, statsPanel)); 
    }//GEN-LAST:event_lblStuDataMouseClicked

    private void lblStuDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStuDataMouseEntered
        LblHover(lblStuData);
    }//GEN-LAST:event_lblStuDataMouseEntered

    private void lblStuDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStuDataMouseExited
        LblHoverOutwo(lblStuData);
    }//GEN-LAST:event_lblStuDataMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            ArrayList<studyante> students = new ArrayList<>();
            new DashboardSidButtons(students).setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ViewPanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblStatistics;
    private javax.swing.JLabel lblStuData;
    private GUI.CustomComponents.MyPanel myPanel1;
    // End of variables declaration//GEN-END:variables
}
